name: Deno CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Deno_code_quality_assurance:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: cd ./deno && deno fmt --check .

      - name: Run linter
        run: cd ./deno && deno lint .

      - name: Run tests
        working-directory: ./deno
        run: deno test -A --unstable
